In [1]:
import numpy as np
A = np.array([1, 2, 3, 4])
print(A)

[1 2 3 4]


In [2]:
np.ndim(A)

1

In [3]:
A.shape

(4,)

In [4]:
A.shape[0]

4

In [7]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
B.shape

(3, 2)

In [10]:
A = np.array([[1, 2], [3, 4]])
A.shape

(2, 2)

In [12]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [13]:
C = np.array([[1, 2, 3], [4, 5, 6]])
D = np.array([[1, 2], [3, 4], [5, 6]])
np.dot(C, D)

array([[22, 28],
       [49, 64]])

In [15]:
E = np.array([[1, 2], [3, 4], [5, 6]])
F = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])
np.dot(E, F)

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [16]:
G = np.array([7, 8])
np.dot(E, G)

array([23, 53, 83])

In [17]:
X = np.array([1, 2])
X.shape

(2,)

In [20]:
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W)
W.shape
W.ndim

[[1 3 5]
 [2 4 6]]


2

In [22]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]
