In [1]:
import numpy as np
print(np.__version__)
np.show_config()

1.15.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [5]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
Z = np.zeros((10,10))
print("Itemsize : %d" % Z.itemsize)
print("Size %d" % Z.size)
print("%d bytes" % (Z.size * Z.itemsize))

Itemsize : 8
Size 100
800 bytes


In [5]:
Z = np.zeros(10)
Z[4]=1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
Z = np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
Z = np.arange(50)
Z[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [10]:
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
Z = np.nonzero([1,2,0,0,4,0])
Z

(array([0, 1, 4]),)

In [12]:
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
Z = np.random.random((3,3,3))
Z

array([[[0.64507654, 0.90255379, 0.01384434],
        [0.83017447, 0.29465757, 0.78963654],
        [0.23507474, 0.36888193, 0.09131354]],

       [[0.75348112, 0.08610906, 0.29682571],
        [0.57522355, 0.23051538, 0.52954872],
        [0.74208766, 0.52376663, 0.13238244]],

       [[0.75857379, 0.44188508, 0.69937036],
        [0.61778142, 0.15067887, 0.75087627],
        [0.28723815, 0.6665976 , 0.75084126]]])

In [16]:
Z = np.random.random((10,10))
print(Z.max(), Z.min())

0.9831255241384719 0.007196357961064437


In [17]:
Z = np.random.random(30)
print(Z.mean())

0.5168646228532409


In [19]:
Z = np.ones(100).reshape((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])